# Generated by Django 2.2 on 2019-05-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='file',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
